/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__WIFI_POINT

#include <ESP8266WiFi.h>

// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "ESP8266 RC Car"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377

#define triggerPin D7
#define echoPin D0
#define IN1 D1
#define IN2 D2
#define IN3 D5
#define IN4 D6

int obstacleCount = 0;
bool autoModeCount = false;
float distance;

#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 89 bytes V19 
  { 255,4,0,0,0,82,0,19,0,0,0,0,179,1,200,84,1,1,4,0,
  5,22,21,41,41,32,2,26,8,1,119,29,24,24,0,2,8,65,117,116,
  111,32,77,111,100,101,0,1,156,29,24,24,0,2,8,77,97,110,117,97,
  108,32,77,111,100,101,0,129,53,3,89,12,64,8,69,83,80,56,50,54,
  54,32,82,67,32,67,97,114,0 };
  
// this structure defines all the variables and events of your control interface 
struct {
    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  uint8_t AutoMode; // =1 if button pressed, else =0, from 0 to 1
  uint8_t ManualMode; // =1 if button pressed, else =0, from 0 to 1
  // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
void moveForward(){
  digitalWrite(IN1, HIGH);
  digitalWrite(IN2, LOW);
  digitalWrite(IN3, HIGH);
  digitalWrite(IN4, LOW); 
}
void moveBackward(){
  digitalWrite(IN1, LOW);
  digitalWrite(IN2, HIGH);
  digitalWrite(IN3, LOW);
  digitalWrite(IN4, HIGH); 
}
void moveRight(){
  digitalWrite(IN1, HIGH);
  digitalWrite(IN2, LOW);
  digitalWrite(IN3, LOW);
  digitalWrite(IN4, HIGH);
}
void moveLeft(){
  digitalWrite(IN1, LOW);
  digitalWrite(IN2, HIGH);
  digitalWrite(IN3, HIGH);
  digitalWrite(IN4, LOW);
}
void stopCar() {
  digitalWrite(IN1, LOW);
  digitalWrite(IN2, LOW);
  digitalWrite(IN3, LOW);
  digitalWrite(IN4, LOW);
}

void obstacleAvoidance(){
  digitalWrite(triggerPin,LOW);
  delayMicroseconds(2);
  digitalWrite(triggerPin,HIGH);
  delayMicroseconds(10);
  digitalWrite(triggerPin,LOW);
  long duration = pulseIn(echoPin, HIGH, 30000);
  distance = (0.0342*duration)/2;
  if(distance > 0 && distance <= 15){
    obstacleCount++;
    stopCar();
    delay(200);
    moveRight();
    delay(200);
    stopCar();
    if(obstacleCount>=2){
      for(int i = 0; i<4 ; i++){
        moveLeft();
        delay(200);
      }
      stopCar();
      obstacleCount=0;
    }
  }
  else{
    obstacleCount = 0;
    moveForward();
  }
}

void setup() 
{
  RemoteXY_Init ();  // initialization by macros 
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(IN3, OUTPUT);
  pinMode(IN4, OUTPUT);
  pinMode(echoPin,INPUT);
  pinMode(triggerPin,OUTPUT);
}

void loop() 
{ 
  RemoteXYEngine.handler ();   
  
  if(RemoteXY.AutoMode == 1){
    autoModeCount = true;
  }
  if(RemoteXY.ManualMode == 1){
    autoModeCount = false;
  }
  if(autoModeCount){
    obstacleAvoidance();
  }
  else{
    if(RemoteXY.joystick_01_y > 50)
      moveForward(); 
    else if(RemoteXY.joystick_01_y < -50)
      moveBackward();
    else if(RemoteXY.joystick_01_x > 50)
      moveRight();
    else if(RemoteXY.joystick_01_x < -50)
      moveLeft();
    else
      stopCar();
  }
}

